name: ICMP9 Checkin

on:
  schedule:
    - cron: "5 0,21 * * *"
  workflow_dispatch:

jobs:
  run:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Setup Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.11"

      - name: Install deps
        run: |
          pip install telethon pysocks

      - name: Run script
        env:
          TG_APIS: ${{ secrets.TG_APIS }}
          TG_SESSIONS: ${{ secrets.TG_SESSIONS }}
          PROXIES: ${{ secrets.PROXIES }}
        run: |
          python icmp9.py
